# Site settings
title: 'Firstheme'
subtitle: 'My first githubpages theme'

description: > # this means to ignore newlines until "baseurl:"
  My first theme for a github page

twitter_username: ulaulaman
github_username:  ulaulaman

# Build settings
markdown: kramdown
